ti-j7xxx: mesa-pvr: Disable pvr PACKAGECONFIG to fix QA error
Issue: LINUXEXEC-36675

The meta-ti commit 80c5d6f12b32f (mesa-pvr: Use PREFERRED_PROVIDER
directly for GPU selection) drops PACKAGECONFIG, Therefore, corresponding
the bbappend drops the pvr PACKAGECONFIG to resolve the following
build error:

ERROR: mesa-pvr-2_24.0.1-r0 do_recipe_qa: QA Issue: mesa-pvr: invalid
PACKAGECONFIG(s): pvr [invalid-packageconfig]
ERROR: mesa-pvr-2_24.0.1-r0 do_recipe_qa: Fatal QA errors were found,
failing task.

The pvr PACKAGECONFIG is not valid in mesa 24.0.1, causing the recipe
QA check to fail.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>